#!/usr/bin/env bash
# vi: ft=sh

export REDIS_HOST=redis.service.consul
export MONGO_HOST=mongo-27017.service.consul

export REDIS_PORT=$(dig $REDIS_HOST SRV | grep SRV | tail -n1 | awk '{print $7}')
export MONGO_PORT=$(dig $MONGO_HOST SRV | grep SRV | tail -n1 | awk '{print $7}')

cat /tyk.conf.template | sed s/\{\{REDIS_HOST\}\}/$REDIS_HOST/g | sed s/\{\{REDIS_PORT\}\}/$REDIS_PORT/g | sed s/\{\{MONGO_HOST\}\}/$MONGO_HOST/g | sed s/\{\{MONGO_PORT\}\}/$MONGO_PORT/g > /opt/tyk-gateway/tyk.conf

cat /opt/tyk-gateway/tyk.conf

/opt/tyk-gateway/tyk --conf=/opt/tyk-gateway/tyk.conf
