#!/usr/bin/env bash
# vi: ft=sh
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $SCRIPT_DIR/shared

read -r -d '' API_BODY << EOF_API
{
    "name": "Tyk Test API",
    "use_keyless": true,
    "proxy": {
        "listen_path": "/quickstart/",
        "target_url": "http://httpbin.org/",
        "strip_listen_path": true
    }
}
EOF_API

#create_api $API_BODY
#create_api '{"name": "Tyk Test API","use_keyless": true,"proxy": {"listen_path": "/quickstart/","target_url": "http://httpbin.org/","strip_listen_path": true}}'


create_api '{"name": "Quickstart test","api_id": "9999999","org_id":"default","definition": {"location": "","key": ""},"use_keyless": true,"auth": {"auth_header_name": ""},"version_data": {"not_versioned": true,"versions": {"Default": {"name": "Default","expires": "3000-01-02 15:04","paths": {"ignored": [],"white_list": [],"black_list": []}}}},"proxy": {"listen_path": "/quickstart/","target_url": "http://httpbin.org/","strip_listen_path": true}}'

#echo -e "$API_BODY"
